### ISSUE TITLE
ProcessParticipantsData

### ISSUE THREAD

**Issue by oyvindMBlaerdal** [PirehP/ARPOSpublic#1]
I would really like to see the code to process signals (denoise and FFT) and the formula to estimate SpO2. where can i find this? Is it a part of "ProcessParticipantsData"? (could not locate this file)

**Comment by gaosir123** [comment]
Hello，
have you found the code for the ProcessParticipantsData part?

**Comment by PirehP** [comment]
This has been added to the public project.

**Comment by gaosir123** [comment]
Is there a module for Check Reliability and Process FaceData?
